# Generated by Django 5.0 on 2024-03-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="myuser",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("hash", models.CharField(max_length=200)),
            ],
        ),
    ]
